### ISSUE TITLE
Problem with CoLab notebook

### ISSUE THREAD

**Issue by drc007** [arneschneuing/DiffSBDD#11]
Great work, just tried using the CoLab notebook and I get this error here.

Run sampling (this will take a few minutes; runtime depends on the input parameters n_samples, timesteps etc.)

Traceback (most recent call last):
  File "/content/DiffSBDD/generate_ligands.py", line 7, in <module>
    from lightning_modules import LigandPocketDDPM
  File "/content/DiffSBDD/lightning_modules.py", line 13, in <module>
    from torch_scatter import scatter_add, scatter_mean
  File "/usr/local/lib/python3.9/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/usr/local/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.9/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs

**Comment by arneschneuing** [comment]
Hi @drc007, it seems that the environment was indeed broken. I changed the installation procedure (579513443d653a321bc2646725948ab44ef857a6) and hope that it works again. 
Please let me know if you encounter further issues.
Thanks,
Arne

**Comment by drc007** [comment]
Works fine now. Thanks, Chris

**Comment by evancollins1** [comment]
This error still occurs for me. I am running the Colab linked in the repo exactly as it exists.

Could you help me? Thanks!
