### ISSUE TITLE
Segmentation fault when running the program

### ISSUE THREAD

**Issue by TommyBiomodellingAU** [arneschneuing/DiffSBDD#41]
i have been trying to download the correct packages for running DiffSBDD, but I get a "Segmentation Fault (core dumped)" after I tried to fix the following error: 

"ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/au649283/anaconda3/envs/sbdd/lib/python3.10/site-packages/rdkit/Chem/../../../../libRDKitFileParsers.so.1)"

I tried doing "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/" to fix the importerror, but now results in seg fault

**Comment by Evert-Homan** [comment]
Same issue on WSL2 Debian 12:

```
 python generate_ligands.py checkpoints/crossdocked_fullatom_cond.ckpt --pdbfile example/3rfm.pdb --outfile example/3rfm_mol.sdf --ref_ligand A:330 --n_samples 20
Traceback (most recent call last):
  File "/home/evehom/Programs/DiffSBDD/generate_ligands.py", line 8, in <module>
    import utils
  File "/home/evehom/Programs/DiffSBDD/utils.py", line 6, in <module>
    from rdkit import Chem
  File "/home/evehom/miniconda3/envs/diffsbdd/lib/python3.12/site-packages/rdkit/Chem/__init__.py", line 16, in <module>
    from rdkit.Chem import rdchem
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.31' not found (required by /home/evehom/miniconda3/envs/diffsbdd/lib/python3.12/site-packages/rdkit/Chem/../../../../libboost_serialization.so.1.86.0)
```

Please advise on how to resolve this.

Thanks/Evert
